### ISSUE TITLE
Tab text not uppercased if only one tab

### ISSUE THREAD

**Issue by mikemcbride** [zpnk/hyper-apex#2]
Sweet package, nice work. I noticed that when you only have one tab open, the tab text isn't uppercased. This is because Hyper uses different classes when there are multiple tabs open. I'd try adding this to `index.js` in your CSS section:

```css
.tabs_title {
   font-size: 11px;
   text-transform: uppercase;
}
```
